// src/services/aiva/constants.js

export const AIVA_INITIAL_GREETING = "Hi there! I'm Aiva, your personal AI assistant. I'm here to simplify your day by helping with receiving and summarizing your files and text, managing your emails, assisting with booking appointments, and even helping you remind about payments. What can I do for you today?";

export const ConversationStates = {
  AWAITING_USER_REQUEST: 'AWAITING_USER_REQUEST',
  AWAITING_INTENT_CONFIRMATION: 'AWAITING_INTENT_CONFIRMATION',
  AWAITING_AFFIRMATIVE_NEGATIVE: 'AWAITING_AFFIRMATIVE_NEGATIVE',
  PROCESSING_PATH_PAYMENT_REMINDER_DETAILS_PROMPT: 'PROCESSING_PATH_PAYMENT_REMINDER_DETAILS_PROMPT',
  AWAITING_CLARIFICATION_FOR_NEGATIVE_INTENT: 'AWAITING_CLARIFICATION_FOR_NEGATIVE_INTENT',
  CONVERSATION_ENDED_OR_COMPLETED_TASK: 'CONVERSATION_ENDED_OR_COMPLETED_TASK',
  PROMPT_EMAIL_MONITORING_PREFERENCES: 'PROMPT_EMAIL_MONITORING_PREFERENCES',
  PROCESSING_EMAIL_MONITORING_PREFERENCES: 'PROCESSING_EMAIL_MONITORING_PREFERENCES',
  AWAITING_CONTENT_FOR_SUMMARY: 'AWAITING_CONTENT_FOR_SUMMARY',
  PROCESSING_APPOINTMENT_DETAILS: 'PROCESSING_APPOINTMENT_DETAILS',
  VALIDATING_APPOINTMENT_DETAILS: 'VALIDATING_APPOINTMENT_DETAILS',
  
  AWAITING_EXTRA_APPOINTMENT_DETAILS: 'AWAITING_EXTRA_APPOINTMENT_DETAILS',
  AWAITING_REMINDER_CONFIRMATION: 'AWAITING_REMINDER_CONFIRMATION',
  AWAITING_APPOINTMENT_CONFIRMATION: 'AWAITING_APPOINTMENT_CONFIRMATION',
};

export const IntentCategories = {
  MONITOR_EMAIL: 'MONITOR_EMAIL',
  SET_REMINDER: 'SET_REMINDER',
  APPOINTMENT_CALL: 'APPOINTMENT_CALL',
  SUMMARIZE_CONTENT: 'SUMMARIZE_CONTENT',
  CONVERSATIONAL_QUERY: 'CONVERSATIONAL_QUERY',
  NONE_OF_THE_ABOVE: 'NONE_OF_THE_ABOVE',
  OUT_OF_CONTEXT: 'OUT_OF_CONTEXT'
};

export const ReplyTypes = {
  DIRECT_ANSWER: 'DIRECT_ANSWER',
  CONTEXTUAL_QUERY: 'CONTEXTUAL_QUERY',
  UNRELATED: 'UNRELATED'
};

export const EmailMonitoringPreferences = {
  NOTIFY_ONLY: 'NOTIFY_ONLY',
  ASSIST_REPLY: 'ASSIST_REPLY',
  BOTH: 'BOTH',
  UNCLEAR: 'UNCLEAR'
};